### ISSUE TITLE
device

### ISSUE THREAD

**Issue by piforce** [olekenneth/pyXcomfort#111]
What do I have to fill in by device? I found in ha the hardware the right usb bus. This gives a list. What do I have to fill in i don't see a 'serial'?

![afbeelding](https://user-images.githubusercontent.com/76213580/203643130-b78ffa9d-d3f3-4c2f-ba0c-f3762d65928c.png)

**Comment by olekenneth** [comment]
This is what I see, when I go into the hardware list in Home Assistant. This is only to find `/dev/ttyUSB0`

<img width="569" alt="image" src="https://user-images.githubusercontent.com/544388/203645004-2eaa419e-5bda-4577-99a4-62264abc7d2a.png">


When you ask about `serial` I think you need to read this: (Because serial is the ID of each light, that you need to get from the Xcomfort-software).
https://github.com/olekenneth/pyXcomfort/tree/master/integrations/home-assistant#add-xcomfort-configurationyaml


Personally I'm using the `supervisor-addon`: 
https://github.com/olekenneth/hassio-addons/tree/master/pyXcomfort

But the configuration is similar.

**Comment by piforce** [comment]
For the Id of the lamps I know what to do en find in the rf manager. 
I get stuck in the addon what to fil in by device* 
I am also using the addon.
![afbeelding](https://user-images.githubusercontent.com/76213580/203704238-5b49b163-8cae-4d91-9c45-273f7d55d84b.png)

**Comment by olekenneth** [comment]
Based on your screenshot: `/dev/bus/usb/001/009` but try with `/dev/ttyUSB0` or `/dev/ttyUSB1` ...

**Comment by olekenneth** [comment]
If you don't it working you can reach me here: https://matrix.to/#/@olekenneth:ablo.xyz

**Comment by piforce** [comment]
Is working know like a charm since update to version 2

**Comment by olekenneth** [comment]
Awesome 👍
